FROM python:3.11-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster_config/dagster.yaml dagster_config/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
