---
x-orchestrator-config: &orchestrator-config
  DAGSTER_POSTGRES_USER: ${DAGSTER_POSTGRES_USER:-postgres_user}
  DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD:-postgres_pass}
  DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB:-postgres_db}

x-sot-config: &sot-config
  INFRAHUB_TOKEN: ${INFRAHUB_TOKEN:-"06438eb2-8019-4776-878c-0941b1f1d1ec"}
  NETBOX_TOKEN: ${NETBOX_TOKEN:-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
  NAUTOBOT_TOKEN: ${NAUTOBOT_TOKEN:-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}

services:
  dagster_postgresql:
    image: postgres:11
    container_name: dagster_postgresql
    environment:
      <<: *orchestrator-config
      POSTGRES_USER: ${DAGSTER_POSTGRES_USER:-postgres_user}
      POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD:-postgres_pass}
      POSTGRES_DB: ${DAGSTER_POSTGRES_DB:-postgres_db}

  orchestrator:
    build:
      context: .
      dockerfile: ./Dockerfile_orchestrator
    container_name: orchestrator
    image: orchestrator_image
    restart: always
    environment:
      <<: [*orchestrator-config, *sot-config]
      DAGSTER_CURRENT_IMAGE: "orchestrator_image"
      INFRAHUB_SDK_API_TOKEN: ${INFRAHUB_TOKEN:-"06438eb2-8019-4776-878c-0941b1f1d1ec"}
    volumes:
      - ./examples-sync-config/:/tmp/sync-config/
      #TODO: Maybe there is room for improvement here e.g. only on prod deployment ... e.g. make this a parameter ...
      - ./workdir-sync-config/:/tmp/workdir-sync-config/

  dagster_webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: dagster_webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      <<: *orchestrator-config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    depends_on:
      - dagster_postgresql
      - orchestrator

  dagster_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    environment:
      <<: *orchestrator-config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    depends_on:
      - dagster_postgresql
      - orchestrator
