---
name: from-netbox
source:
  name: netbox
  settings:
    url: "https://demo.netbox.dev"

destination:
  name: infrahub
  settings:
    url: "http://infrahub-server:8000"

store:
  type: redis
  settings:
    host: cache
    port: 6379

order: [
  "BuiltinTag",
  "LocationBuilding",
]

schema_mapping:
  # Tags
  - name: BuiltinTag
    mapping: extras.tags
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  # Sites (Region & Sites)
  - name: LocationBuilding
    mapping: dcim.sites
    identifiers: ["shortname"]
    fields:
      - name: name
        mapping: name
      - name: shortname
        mapping: slug
      - name: description
        mapping: description
      - name: physical_address
        mapping: physical_address
      - name: tags
        mapping: tags
        reference: BuiltinTag

